<h3> Conozca un Arreglo numpy  </h3>

Utilizará el arreglo numpy <code> A</code> para lo siguiente  

In [1]:
import numpy as np
A=np.array([[11,12],[21,22],[31,32]])


1) escriba usando la función 'type' 

In [2]:
type(A)

numpy.ndarray

2) la forma del arreglo 

In [3]:
A.shape

(3, 2)

3) el tipo de datos en el arreglo 

In [4]:
A.dtype

dtype('int64')

4) Encuentre la segunda fila del arreglo numpy <code>A</code>:

In [6]:
A[1][:]

array([21, 22])

<h3> Dos tipos de Multiplicación    </h3>

utilizará los siguientes arreglos numpy para las siguientes preguntas 

In [7]:
A=np.array([[11,12],[21,22]])
B=np.array([[1, 0],[0,1]])

1) multiplique la matriz <code> A </code> y <code>B</code> 

In [8]:
A*B

array([[11,  0],
       [ 0, 22]])

2) trazar la función

In [9]:
np.dot(A,B)
np.dot(B,A)



array([[11, 12],
       [21, 22]])

<hr>
<small>Copyright &copy 2020 IBM Cognitive Class. Este cuaderno y su código fuente se publican bajo los términos de la [Licencia MIT] (https://cognitiveclass.ai/mit-license/).

</small>

In [10]:
#cuántas filas es la siguiente matriz numpy:

A=np.array([[1,2],[3,4],[5,6],[7,8]]) 
A.shape

(4, 2)

In [11]:
#¿Se puede realizar la siguiente operación?

A=np.array([[1,2],[3,4],[5,6],[7,8]])

B=np.array([[1,2,3],[4,5,6],[7,8,9]])

np.dot(A,B) 

ValueError: shapes (4,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)