<a href="https://colab.research.google.com/github/raaraya1/Personal-Proyects/blob/main/Canales%20de%20Youtube/Sentdex/Pytorch/Taller1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

x = torch.Tensor([5, 3])
y = torch.Tensor([2, 1])

print(x*y)

tensor([10.,  3.])


In [ ]:
x = torch.zeros([2, 5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


x.shape

In [ ]:
y = torch.rand([2, 5])
y

tensor([[0.1673, 0.1530, 0.1973, 0.8791, 0.1623],
        [0.3085, 0.4254, 0.9303, 0.5905, 0.4349]])

In [ ]:
y.view([1, 10])

tensor([[0.1673, 0.1530, 0.1973, 0.8791, 0.1623, 0.3085, 0.4254, 0.9303, 0.5905,
         0.4349]])

In [ ]:
y = y.view([1, 10])
y

tensor([[0.1673, 0.1530, 0.1973, 0.8791, 0.1623, 0.3085, 0.4254, 0.9303, 0.5905,
         0.4349]])